name: Deploy Website Sekolah

on:
  push:
    branches:
      - main # Ini berarti deploy jalan tiap lu push ke branch main

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        # Perhatikan tulisan secrets.NAMA_SECRET nya, harus sama dengan yang di GitHub
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
        # 'server-dir' adalah folder tujuan di cPanel. 
        # Biasanya public_html atau public_html/subfolder
        server-dir: ./public_html/
